### ISSUE TITLE
KotlinNullPointerException on `antlr` dependency

### ISSUE THREAD

**Issue by martinbonnin** [autonomousapps/dependency-analysis-android-gradle-plugin#300] opened 2020-10-09 11:10 UTC
Reproducer project there: https://github.com/martinbonnin/test-antlr/

Calling `./gradlew buildHealth --stacktrace` fails with:

```
Caused by: kotlin.KotlinNullPointerException
        at com.autonomousapps.internal.ConsoleReport$Companion.from(models.kt:487)
        at com.autonomousapps.tasks.BuildHealthTask.action(BuildHealthTask.kt:46)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
```

This only happens on current `main`. The sample projects expects `0.61.1-SNAPSHOT` in mavenLocal. `0.61.0` is ok (although it displays "null" for configurations). I guess it has to do with the fact that the `antlr` plugin adds the dependency automagically.

**Comment by autonomousapps** [comment] 2020-10-09 17:49
Huh, that's strange. The antlr project is simple added directly to the jar (see [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/build.gradle.kts#L81) and [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/build.gradle.kts#L121)).

The reproducer is appreciated.

**Comment by autonomousapps** [comment] 2020-10-09 23:27
Well, I can get it to recognize the `antlr` configuration, but it still reports the dependency as unused (incorrectly, I assume)

```
> Task :buildHealth
Advice for root project
Unused dependencies which should be removed:
- antlr("org.antlr:antlr4:4.8-1")

Transitively used dependencies that should be declared directly as indicated:
- api("org.antlr:antlr4-runtime:4.8-1")
```

**Comment by autonomousapps** [comment] 2020-10-09 23:30
I have used antlr, but it's been a while. Do you have an idea why the plugin wouldn't "see" any code from that jar being used? Btw, once I merge to main, you can add this to ignore the false warning
```kotlin
dependencyAnalysis {
  issues {
    all {
      onUnusedDependencies {
        exclude("org.antlr:antlr4")
      }
    }
  }
}
```

**Comment by martinbonnin** [comment] 2020-10-10 07:46
I think it's correct that `antlr` isn't used. It's the compiler that is used at compile time but at runtime only `antlr-runtile` is used (transitively)

**Comment by autonomousapps** [comment] 2020-10-10 07:56
Ah, I see. So the plugin should probably make it a compileOnly
dependency. Hm. Maybe we can just upstream this. 

On October 9, 2020, GitHub <notifications@github.com> wrote:
> I think it's correct that antlr isn't used. It's the compiler that is

> used at compile time but at runtime only antlr-runtile is used
> (transitively)
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-

plugin/issues/300#issuecomment-706506339>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PL2H46BI7ZOEY3KVT3SKAGPJANCNFSM4SJ6BA2Q>.

**Comment by autonomousapps** [comment] 2020-10-12 00:34
While I have merged the PR, this issue is not quite resolved to my satisfaction.

**Comment by autonomousapps** [comment] 2020-10-12 00:43
Here it is, the antlr plugin sets the compile configuration as a descendant of the antlr configuration https://github.com/gradle/gradle/blob/master/subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java#L67-L68

**Comment by autonomousapps** [comment] 2020-10-12 03:07
I'm starting to think what I actually need is special-handling for non-standard configurations. This is now a design question.

**Comment by martinbonnin** [comment] 2020-10-12 08:17
> Here it is, the antlr plugin sets the compile configuration as a descendant of the antlr configuration

That's interesting... Is there a reason to do this instead of adding `antlr-runtime` to the `compileClasspath` configuration, like [SQLDelight is doing](https://github.com/cashapp/sqldelight/blob/master/sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt#L87)

> I'm starting to think what I actually need is special-handling for non-standard configurations. This is now a design question.

I guess part of why that's hard here because it's hard to tell whether a given dependency was added by the user or by another plugin?...

**Comment by autonomousapps** [comment] 2020-10-12 17:31
For me, I think I just need to draw the line somewhere. I can't support every plugin out of the box. But to avoid giving bad information to users, I think I might have the plugin ignore dependencies that are on a custom, not-well-known, configuration. 

I can imagine supporting additional plugins (like antlr), but that won't solve the general case, which is what I'm talking about now.

**Comment by autonomousapps** [comment] 2020-10-14 01:01
The latest PR resolves this in a more general and satisfying way. The plugin should now ignore all "unusual" configurations. We can add support for them one at a time as it may seem useful.

**Closed** 2020-10-14 19:02 UTC
Labels: bug
