### ISSUE TITLE
Class scanning fails with java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sdf-cnicorp** [autonomousapps/dependency-analysis-android-gradle-plugin#239] opened 2020-07-28 17:08 UTC
[dependency-analysis-shortened.log](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/4989991/dependency-analysis-shortened.log)
[dependency-graph.txt](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/4989994/dependency-graph.txt)

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 32800 out of bounds for length 15
  at com.autonomousapps.internal.asm.ClassReader.readUtf(ClassReader.java:3641)

Last line of debug log:
 [DEBUG] [org.gradle.api.Task] ClassNameCollector#visit: PACKAGE_PRIVATE org/objectweb/asm/all/module-info extends null

**Comment by autonomousapps** [comment] 2020-07-28 17:21
Thank you for the report! Looks like a bug.

**Comment by autonomousapps** [comment] 2020-07-28 17:22
If you had a stacktrace or build scan, that would also help.

**Comment by sdf-cnicorp** [comment] 2020-07-28 17:30
Stacktrace is in the file 'dependency-analysis-shortened.log' attached above.

**Comment by autonomousapps** [comment] 2020-07-28 18:27
What version of the plugin are you using? What version of Java are you building with? (questions like this are why I ask for a build scan).

**Comment by sdf-cnicorp** [comment] 2020-07-29 17:31
As shown in the attached log, this was found using version 0.55.0.

**Comment by autonomousapps** [comment] 2020-07-29 18:25
What version of Java are you building with? Which version of the ASM lib are you using?

**Comment by sdf-cnicorp** [comment] 2020-07-29 19:18
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Zulu11.33+15-CA (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.33+15-CA (build 11.0.4+11-LTS, mixed mode)

I am not using asm directly, it is a transitive dependency. As you can see from the attached dependency graph, there are several versions of the asm library included and I do not know which is causing the problem.

**Comment by autonomousapps** [comment] 2020-07-29 20:46
Thank you. One of the reasons I've been harping on the question about your Java version is that the logs visited a file `org/objectweb/asm/all/module-info`, which certainly indicated you were at least on Java 9. The plugin should not be trying to visit a module-info file. With this new information I might now be able to debug your issue.

**Comment by autonomousapps** [comment] 2020-08-10 00:01
Thank you for your patience. I believe I may have a fix for this. Unfortunately, I was not able to reproduce. But assuming the issue was analyzing the module-info.class file, then the associated PR resolves this issue. Are you able to test with a snapshot, before I publish?

**Comment by autonomousapps** [comment] 2020-08-10 04:38
I did not mean for this to be closed.

**Comment by sdf-cnicorp** [comment] 2020-08-10 13:11
Yes, I can test. How do I get the snapshot?

**Comment by autonomousapps** [comment] 2020-08-10 17:22
Thanks. I have a section in [the wiki](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Adding-to-your-project) explaining the various ways to add the plugin to a project, including using snapshots. You'll want to use `0.56.1-SNAPSHOT` (this version is visible as a badge at the top of the [readme](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin)).

**Comment by autonomousapps** [comment] 2020-08-19 17:58
Hi @sdf-cnicorp , have you had a chance to test a snapshot?

**Comment by sdf-cnicorp** [comment] 2020-08-19 18:16
Sorry, but no. Rush project at work… Should get back to this early next week, if not before.

**Comment by autonomousapps** [comment] 2020-09-01 02:57
I just this morning released 0.57.0, which I believe resolves this issue. I'm going to close this for now, but please feel free to reopen if you still see the issue.

**Closed by autonomousapps** 2020-09-01 02:57 UTC
Labels: bug
