### ISSUE TITLE
Exclude used transitive dependencies only if they are provided by given module

### ISSUE THREAD

**Issue by Kostyshina** [autonomousapps/dependency-analysis-android-gradle-plugin#353] opened 2020-12-30 09:04 UTC
**Problem situation**
We have some common module in project that is used to unite some dependencies and functionalities. That module has api dependencies that we don't want to add directly in other modules that will be using this one, because the whole point of this module: is to provide those dependencies (for example common-network that depends on retrofit and gson and provide some common stuff). But if this module is not added, and dependencies provided with other module through api - we don't want to ignore them

**Possible solution**
So it will be very cool to have possibility to list `onUsedTransitiveDependencies` that will be applied only if corresponding module is added as a dependency (of course if it's added  to other module with implementation and we need to add api for some of the transitive dependencies only, and not for whole module, we will need to add them directly)

**Comment by Kostyshina** [comment] 2021-01-11 10:22
we have tried [bundles](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#logical-dependency-groups-aka-dependency-bundles), but it seems to not work as expected

**Comment by Jacks0N23** [comment] 2021-01-11 10:27
or bundles documentation not clearly describe how it works, and we use it not as intended

**Comment by autonomousapps** [comment] 2021-01-11 22:14
> bundles don't seem to work as expected.

That _looks_ like a bug. I'll need to investigate, but I think what you tried ought to work. I have a [unit test](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/test/kotlin/com/autonomousapps/extension/BundleHandlerTest.kt) for this, but it looks like I don't have any functional tests. If you could provide a repro that is just a PR with a failing unit test, that would be helpful.

**Comment by Kostyshina** [comment] 2021-01-12 13:55
Seems like bundles working properly, and our module missed dependency we needed. Sorry for this

**Comment by autonomousapps** [comment] 2021-02-08 18:48
I'm going to close this for now. If you feel that the usage of bundles doesn't capture the intent, please feel free to reopen.

**Closed by autonomousapps** 2021-02-08 18:48 UTC
Labels: bug
