### ISSUE TITLE
Tasks are not registered if project has been evaluated

### ISSUE THREAD

**Issue by mqueiroz1995** [autonomousapps/dependency-analysis-android-gradle-plugin#284] opened 2020-09-18 21:26 UTC
**Plugin version**
v0.59.0

**Gradle version**
v6.1.1

**Android Gradle Plugin (AGP) version**
v3.6.4

**Describe the bug**

Most of the plugin's tasks are registered in the projects inside `afterEvaluate` closure. For example, take a look at `Project.configureAndroidAppProject` in `DependencyAnalysisPlugin`.

Unfortunately,  [the closure is ignored when added to an evaluated project](https://github.com/gradle/gradle/issues/1135).  The project I'm working on is a big project with both native and React Native code, and when the plugin is applied some of the subprojects have already been evaluated. Because of that, the tasks are not registered, `dependencyAdvice`, `redundantKaptAdvice` and `redundantJvmAdvice` are always empty and `aggregateAdvice` is always skipped. 

**To Reproduce**

Couldn't reproduce in dummy project 😢 

After generating a modified version of the plugin where those tasks are registered when the function is called, instead of inside after evaluate, everything worked fine. 

**Expected behavior**

If the project has been evaluated previously, the plugin has all required information and tasks should be registered. So the plugin [should validate project's state](https://github.com/gradle/gradle/issues/9395) and, if evaluated, should register all tasks, if not, set the closure.

**Additional context**

In this project, `org.gradle.configureondemand` is set to true.

**Comment by autonomousapps** [comment] 2020-09-18 21:35
Can you tell me if this behavior can be reproduced WITHOUT configuration on demand? Because what you're saying doesn't make much sense to me. Gradle should run my afterEvaluate code, period. I have never seen a case where it doesn't, and have never read any documentation indicating it might skip it.

Those callbacks are unfortunately required to handle various cases involving the interaction of more than two plugins (e.g., my plugin, the Android plugin, and the Kotlin plugin).
GitHub <notifications@github.com> wrote:
“Plugin version
 v0.59.0

Gradle version
 v6.1.1

Android Gradle Plugin (AGP) version
 v3.6.4

Describe the bug

Most of the plugin's tasks are registered in the projects inside afterEvaluate closure. For example, take a look at Project.configureAndroidAppProject in DependencyAnalysisPlugin.

Unfortunately, the closure is ignored when added to an evaluated project. The project I'm working on is a big project with both native and React Native code, and when the plugin is applied some of the subprojects have already been evaluated. Because of that, the tasks are not registered, dependencyAdvice, redundantKaptAdvice and redundantJvmAdvice are always empty and aggregateAdvice is always skipped.

To Reproduce

Couldn't reproduce in dummy project 😢

After generating a modified version of the plugin where those tasks are registered when the function is called, instead of inside after evaluate, everything worked fine.

Expected behavior

If the project has been evaluated previously, the plugin has all required information and tasks should be registered. So the plugin should validate project's state and, if evaluated, should register all tasks, if not, set the closure.

Additional context

In this project, org.gradle.configureondemand is set to true.”

**Comment by mqueiroz1995** [comment] 2020-09-19 22:13
Thanks for the quick response.

Just ran the same experiment with configuration on demand and the same behavior still happens.

I linked an issue on gradle's github pointing out that this behavior is intentional and not gonna be changed because it's a breaking change: https://github.com/gradle/gradle/issues/1135

**Comment by autonomousapps** [comment] 2020-09-19 22:28
Thanks, I'll take a look. I would really like to find some way to reliably reproduce this so I can validate any change I might make.

**Comment by mqueiroz1995** [comment] 2020-09-21 13:48
Found a way to force eager project evaluation and reproduce the issue.

In your root `build.gradle` add the following code:

```groovy
allprojects {
    ...

    getTasksByName('tasks', false) // this makes all projects evaluate eagerly
}
```

Then apply the plugin and see that the code inside the closure does not execute.

**Comment by autonomousapps** [comment] 2020-09-21 17:03
One thing I don't understand is why you would do this. What is the real life scenario where you're late-adding the plugin?

**Comment by mqueiroz1995** [comment] 2020-09-21 17:23
Today I was able to spot and fix what was causing this issue, so now your plugin works fine in our project (for instance, it was exactly a call to `getTasksByName` that was causing the issue).

Maybe this issue is still valid because of the way Gradle handles `afterEvaluate` and a fix would be welcome. Maybe it's a edge case that is not worth attention. Feel free to close the issue if you think it's not worth addressing the issue.

**Comment by autonomousapps** [comment] 2020-09-26 03:22
I'm afraid I do not think it tenable to check if a project has already been evaluated, so I will close this for now. Thank you for discussing it with me.

**Closed by autonomousapps** 2020-09-26 03:22 UTC
