### ISSUE TITLE
Moshi annotation processor not recognized

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#454] opened 2021-08-26 20:57 UTC
**Build scan link**

Reproducer
[kapt-moshi.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/7062655/kapt-moshi.zip)

**Plugin version**

0.76.0

**Gradle version**

7.0 and 7.2

**(Optional) Android Gradle Plugin (AGP) version**

4.2.1 and 7.0.1

**Describe the bug**

I'm using Moshi's annotation processor through kapt. When running `buildHealth` I get

```
> Task :settings:findDeclaredProcsDebug
Could not reflectively access processor class com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor

> Task :buildHealth
Advice for root project
Looking good! No changes needed

Advice for project :settings
Plugin advice:
- kotlin-kapt: this project has the kotlin-kapt (org.jetbrains.kotlin.kapt) plugin applied, but no annotation processors (or no used annotation processors), which is redundant.

BUILD SUCCESSFUL in 1s
```

So it seems that the plugin specifically fails to access `JsonClassCodegenProcessor` and then reports kapt as unused because there are no other processors.

**To Reproduce**
1. Add `kapt("com.squareup.moshi:moshi-kotlin-codegen:1.12.0")` to a project
2. Declare a data class with `@JsonClass(generateAdapter = true)` 

**Expected behavior**

kapt is not reported as unused.

**Additional context**

This is the only processor where I see this happening, others like Dagger or moshi-sealed seem fine. 

Side note: Even when adding 
```
issues {
    all {
        onAny {
            severity('fail')
        }
    }
}
```
the plugin reporting kapt as unused does not fail the build. Might be another bug.

**Comment by autonomousapps** [comment] 2021-08-28 17:31
Once again, thanks for the reproducer.

**Comment by autonomousapps** [comment] 2021-08-28 19:26
I think that 
```groovy
issues {
    all {
        onAny {
            severity('fail')
        }
    }
}
```
is another, or maybe just a misleading API. `onAny` only configures _dependency_ violations, vs _plugin_ violations. You could use `onRedundantPlugins` instead. If you think that should have different behavior, would you please file a feature request?

**Comment by autonomousapps** [comment] 2021-08-28 21:02
Resolved via related PR.

**Closed by autonomousapps** 2021-08-28 21:02 UTC
Labels: bug

**Comment by gabrielittner** [comment] 2021-08-29 10:08
> I think that ... is another, or maybe just a misleading API. onAny only configures dependency violations, vs plugin violations. You could use onRedundantPlugins instead. If you think that should have different behavior, would you please file a feature request?

The API is a bit misleading I'd say. I think it would be enough to update that you have on the configuration snippet here https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#failure-conditions-and-filtering

**Comment by autonomousapps** [comment] 2021-08-30 00:23
I agree it's confusing. It's a historical artifact. The plugin didn't originally give advice regarding plugins. Do you mind filing an issue?

**Comment by gabrielittner** [comment] 2021-08-30 11:17
Opened #462 


After updating to `0.77.0` the fix for moshi works but I noticed that the processor analysis also fails on Dagger: `Could not reflectively access processor class dagger.internal.codegen.ComponentProcessor`. I guess I didn't notice it before because we only have dagger in 3 checked projects and our build is fairly noisy. Do you want an extra reproducer for dagger?

**Comment by autonomousapps** [comment] 2021-08-30 15:57
Sure, those always help. 

On August 29, 2021, GitHub ***@***.***> wrote:
> Opened #462 <https://github.com/autonomousapps/dependency-analysis-
> android-gradle-plugin/issues/462>
>
> After updating to 0.77.0 the fix for moshi works but I noticed that
> the processor analysis also fails on Dagger: Could not reflectively
> access processor class dagger.internal.codegen.ComponentProcessor. I
> guess I didn't notice it before because we only have dagger in 3
> checked projects and our build is fairly noisy. Do you want an extra
> reproducer for dagger?
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/454#issuecomment-908258458>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PPMAHY427ECLG5OFS3T7NSEZANCNFSM5C4FKUHQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
