### ISSUE TITLE
Inconsistent ignoreKtx behavior

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#401] opened 2021-05-19 22:09 UTC
**Build scan link**

Here is a sample project instead 
[sample.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/6511748/sample.zip)

**Plugin version**

0.73.0

**Gradle version**

7.0.2

**Android Gradle Plugin (AGP) version**

4.2.1

**Describe the bug**

The project has `ignoreKtx(true)` set and gets this report:
```
Transitively used dependencies that should be declared directly as indicated:
- implementation("androidx.lifecycle:lifecycle-viewmodel:2.3.1")
```
It already has this dependency: `implementation libs.androidx.viewmodel.runtime` which is defined as `androidx-viewmodel-runtime = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }`. 

**To Reproduce**
1. run `./gradlew :confetti:projectHealth`

**Expected behavior**

No advice is reported as `lifecycle-viewmodel-ktx` is present.

**Additional context**

Weirdly here it only affects `projectHealth` and not `buildHealth`, the latter does not report any issues. Adding
```
dependencyAnalysis {
    issues {
        ignoreKtx(true)
    }
}
```
to the subproejct does not change anything so it doesn't seem to be a propagation error. 

Declaring a bundle in the root project resolves it
```
bundle("androidx-viewmodel") {
    includeDependency("androidx.lifecycle:lifecycle-viewmodel")
    includeDependency("androidx.lifecycle:lifecycle-viewmodel-ktx")
}
```

In my work project weirdly `buildHealth` is also affected, however there we apply the plugin on subprojects in a precompiled script plugin and disable `autoApply`. I can dig into this separately if it still happens after the issue that also happens in the sample project is fixed.

**Comment by autonomousapps** [comment] 2021-05-27 22:37
Thanks for the detailed report, much obliged!

**Comment by autonomousapps** [comment] 2021-06-19 19:56
It turns out this is working as intended, although I admit it's a bit confusing (enough that I had to debug a bit to remind myself of the original intent).

First, the reason it seemed to be working for `buildHealth` but not for `projectHealth` is that you had turned strict mode off. Strict mode is only relevant for the global analysis. If you turn it back on, then you'll see both tasks suggest declaring the transitive dependency.

Ok, so what is the intent of `ignoreKtx(true)`? The purpose is to _not_ suggest removing the `-ktx` dependency if one of its transitives are used. That's the very common situation the plugin tries to help out with. Your sample project does not fall into this category. It uses both the ktx dependency and its transitive dependency. In strict mode, the plugin will suggest declaring all transitive dependencies that are used.

I even found an instance of Kdoc that describes this incorrectly, which I will update.

If you think this behavior could be improved, then what you have is a feature request rather than a bug report. Does that all make sense?

**Comment by gabrielittner** [comment] 2021-06-20 08:26
Thanks for looking into it and the detailed explanation. I think it would make sense to change this to a feature request. 

A common pattern is to only add the `-ktx` version of a dependency if one is available. So a dependency catalog usually only declares the `-ktx` artifacts as well. I think in the same way that `ignoreKtx` does not suggest removing a `-ktx` dependency when the non `-ktx` artifact is used, it would make sense to also not suggest adding the non `-ktx` artifact. Both cases have the same motivation for me, letting users only declare `-ktx` dependencies.

If you think this shouldn't be part of `ignoreKtx`, maybe there could be an `automaticKtxBundles` feature? That could automatically create a bundle for each ktx dependency the plugin encounters. Although I'm not sure right now if bundles would only cover the the "used transitive dependency" case or also the don't suggest removing the `-ktx` dependency case that `ignoreKtx` covers.

**Comment by autonomousapps** [comment] 2021-08-29 00:45
Since this is working as intended (even though it's confusing), and because it can be resolved via the bundle feature, I'm removing this from milestone 1.0. I'm trying to avoid new features before v1, so I can focus on fixing bugs.

**Comment by gabrielittner** [comment] 2021-08-29 08:39
👍 

I was also able to make the bundle creation nicer by adding this which does it automatically for all ktx artifacts in our version catalog
```
def catalogs = project.extensions.getByType(VersionCatalogsExtension)

dependencyAnalysis {
    dependencies {
        def catalog = catalogs.named("libs")
        catalog.dependencyAliases.forEach { dependencyAlias ->
            def dependency = catalog.findDependency(dependencyAlias).get().forUseAtConfigurationTime().get()
            def module = dependency.module

            if (module.name.endsWith("-ktx")) {
                bundle("${module.group}-${module.name}") {
                    includeDependency("${module.group}:${module.name}")
                    includeDependency("${module.group}:${module.name.replace("-ktx", "")}")
                }
            }
        }
    }
}
```

**Comment by autonomousapps** [comment] 2022-05-21 17:15
@gabrielittner I suspect that the rewritten bundle/ktx support in v1.0+ now does [this](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/401#issuecomment-907753470) and you can remove your workaround. See the code [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/internal/Bundles.kt#L104-L112). Basically, with v1, I re-implemented the `ignoreKtx` feature as a kind of dynamic bundle.

There's also a related feature, new in 1.2 I think where you can call the `bundle.primary()` function to set the "primary identifier" of a bundle. This is relevant in this situation because, arguably, the `-ktx` dependency should be considered the "primary" for these dynamic ktx bundles. The code I'm pointing you at doesn't yet do that, but it could.

If you do get a chance to try it out, I'd love to hear your feedback and if this works for you without your workaround.

**Closed** 2022-05-22 23:28 UTC
Labels: enhancement

**Comment by gabrielittner** [comment] 2022-05-23 14:49
I've tried it out and it works the same after removing the workaround 👍 

I think setting primary would be a nice to have but at least for us it doesn't matter much because we only have the ktx variants in our version catalog, so in practice people can't even use the wrong one.
