### ISSUE TITLE
Unused testImplementation dependencies are not reported

### ISSUE THREAD

**Issue by Dim0N22** [autonomousapps/dependency-analysis-android-gradle-plugin#366] opened 2021-02-11 23:32 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to remove unused dependencies in my project. Particularly I have unused `testImplementation` dependencies that are not reported by the plugin.

**Describe the solution you'd like**
`testImplementation` dependencies should be reported as unused if they are not needed in tests.

**Additional context**
I've created a repro: https://github.com/Dim0N22/dependency-analysis-android-gradle-plugin-testImplementation-bug-repro.

Steps to reproduce:
```
git clone https://github.com/Dim0N22/dependency-analysis-android-gradle-plugin-testImplementation-bug-repro.git
chmod +x ./gradlew
./gradlew buildHealth
```

**Output**
```
❯ ./gradlew buildHealth

> Task :buildHealth
Advice for root project
Looking good! No changes needed

Advice for project :lib
Unused dependencies which should be removed:
- implementation("com.google.guava:guava:29.0-jre")
- api("org.apache.commons:commons-math3:3.6.1")
```

**Expected output**
Since [the library build script](https://github.com/Dim0N22/dependency-analysis-android-gradle-plugin-testImplementation-bug-repro/blob/main/lib/build.gradle#L15) contains an unused `testImplementation` dependency on `org.robolectric:robolectric:3.8`, it should be reported by `./gradlew buildHealth`.

**Comment by autonomousapps** [comment] 2021-04-18 18:03
Thanks for the reproducer! That will make it a lot easier to dig into. I wonder if Robolectric is only used at runtime.... I wonder what would happen if you used the [Reason feature](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Tasks#reason)?
```
./gradlew lib:reason --id org.robolectric:robolectric
```
that feature is a work in progress and so may or may not be useful in this situation.

**Comment by autonomousapps** [comment] 2021-06-14 05:59
I've reproduced this and understand the reason. A fix will be forthcoming.

**Comment by autonomousapps** [comment] 2021-06-18 05:12
This will be released as 0.74.0.

**Closed** 2021-06-18 05:11 UTC
Labels: bug, question

**Comment by eugene-krivobokov** [comment] 2021-06-21 10:17
I see new issues about this new behavior: #423, #425, #424. 
They force to add many ignores a multi-module project or disable the check.

How about adding an experimental feature toggle for new behavior?

**Comment by autonomousapps** [comment] 2021-06-21 16:01
This plugin is in a prerelease state, as indicated by the leading zero. As such, it does not support experimental toggles. 

That said, I already have a fix for one of those issues, and a WIP for another.
