### ISSUE TITLE
Setting onAny with severity("ignore") supersedes any finer-grain configurations set in the same block

### ISSUE THREAD

**Issue by kyhule** [autonomousapps/dependency-analysis-android-gradle-plugin#629] opened 2022-04-06 03:44 UTC
**Build scan link** 
https://scans.gradle.com/s/ltknlvd7vutuu

**Plugin version**
1.0.0-RC05

**Gradle version**
7.3.3, 7.4.2

**(Optional) Android Gradle Plugin (AGP) version**
7.1.2, 7.2.0-beta04

**Describe the bug**
Setting `onAny` with `severity("ignore")` supersedes any finer-grain configurations set in the same block.
```
dependencyAnalysis {
    issues {
        all {
            // setting this supersedes any finer-grain configurations that set a higher severity
            onAny {
                severity("ignore")
            }

            // these don't do anything
            onUnusedDependencies {
                severity("fail")
            }
            onUnusedAnnotationProcessors {
                severity("fail")
            }
            onRedundantPlugins {
                severity("fail")
            }
        }
    }
}
```

**To Reproduce**
Run `buildHealth` on [sample project](https://github.com/kyhule/dep-analysis-onany-union-issue)

**Expected behavior**
build should fail for unused kapt and unused dependencies.

**Additional context**
Build succeeds and build-health-report.txt is empty.

**Comment by autonomousapps** [comment] 2022-04-06 20:53
Thanks for the issue. When you say "on sample project", can you clarify what that means?

**Comment by kyhule** [comment] 2022-04-07 01:37
I could have swore I included a link to a sample project but I seemed to have lost my mind. Added it to original issue to make your question look crazy but here it is as well https://github.com/kyhule/dep-analysis-onany-union-issue 🙃

**Comment by autonomousapps** [comment] 2022-05-31 23:54
I have decided this is indeed annoying and it should be possible to specify looser rules in a subproject.

**Comment by autonomousapps** [comment] 2022-05-31 23:57
Ah, looks like this duplicates https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/409.

**Comment by autonomousapps** [comment] 2022-06-20 05:12
@kyhule at the moment, I'm thinking I don't want to resolve this. I think that, if you want to have specific handling for issue types, you should _not_ use `onAny`. Also, upon further inspection, this isn't actually a duplicate of https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/409, which is about the ability to change behavior in subprojects vs the root severity setting.

**Closed by autonomousapps** 2022-06-20 05:12 UTC
Labels: enhancement
