### ISSUE TITLE
Project version must be considered as input when using Gradle build cache

### ISSUE THREAD

**Issue by Paladinium** [autonomousapps/dependency-analysis-android-gradle-plugin#164] opened 2020-05-13 12:40 UTC
**Plugin version**
v0.41.0

**Gradle version**
6.3

**Android Gradle Plugin (AGP) version**
None

**Describe the bug**
We're using the [Gradle build cache](https://docs.gradle.org/current/userguide/build_cache.html) to speed up the build. Most tasks of this plugin are annotated with `@CacheableTask`. Therefore, Gradle is caching the outputs produced.

Some files like `artifacts-pretty.json` contain the version and path on disk of dependent JARs. Those JARs may not only be 3rd party libs, but also dependencies in a multi-project-build.

If the Gradle project's version changes, the cached files point to invalid files resulting in errors like:

```
06:32:37 Execution failed for task ':core:inlineMemberExtractorMain'.
06:32:37 > A failure occurred while executing com.autonomousapps.tasks.InlineMemberExtractionWorkAction
06:32:37    > /var/jenkins/workspace/some-job/my-dependent-module/build/libs/my-dependent-module-7.3.jar
```

**To Reproduce**
Along the line of:
1. Setup a multi-project build with 2 modules: A and B with A depending on B
2. Define a version in Gradle, e.g. 1.0
3. Verify that the JARs build with Gradle contain the version in it's JAR file name
4. Make sure one of the tasks leading to the error is always running, e.g.: 
```
tasks.withType<ConstantUsageDetectionTask>().configureEach {
	outputs.upToDateWhen { false }
}
```
5. Update the version to e.g. 1.1
6. Manually delete the build folder of B (otherwise, the old JAR might still be here)
7. Run `gradlew A:constantUsageDetectorMain`
8. You should see the build fail

**Expected behavior**
Changing the project's version should invalidate all outputs produced by this plugin.

**Potential solution**
The project version should be an input to this plugin's tasks for each task producing files. When the version changes, the inputs change and Gradle should re-run the affected tasks.

**Comment by autonomousapps** [comment] 2020-05-13 20:35
I'm not really following along here. If a version change has the effect of changing the path to a project's artifact, then the input to the `ArtifactsAnalysisTask` (which produces `artifacts-pretty.json`) should also change, resulting in task/cache invalidation and re-execution of the task. In other words, I'm not clear on how the version of a project isn't _already_ accounted for.

A reproducer and a build scan might help.

**Comment by Paladinium** [comment] 2020-05-14 08:01
What we see in the logs are, that ArtifactsAnalysisTask is taken from Cache without re-run:

```
06:32:32 > Task :core:locateDependenciesMain FROM-CACHE
06:32:32 > Task :core:artifactsReportMain FROM-CACHE
06:32:32 > Task :core:dependenciesReportMain FROM-CACHE
06:32:33 > Task :core:abiAnalysisMain FROM-CACHE
06:32:33 > Task :core:findDeclaredProcsMain FROM-CACHE
06:32:33 > Task :core:importFinderMain FROM-CACHE
06:32:33 > Task :core:findUnusedProcsMain FROM-CACHE
06:32:33 > Task :core:analyzeClassUsageMain FROM-CACHE
06:32:33 > Task :core:constantUsageDetectorMain FAILED
06:32:33 > Task :core:inlineMemberExtractorMain FAILED
```

I guess the bug can be explained as follows:

- `ArtifactsAnalysisTask` gets [its input](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/b2bd81834b9eaa76fb1a1c1260458df2bfced110/src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt#L399) from `locateDependencies`
- `LocateDependenciesTask` gets [its input](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/b2bd81834b9eaa76fb1a1c1260458df2bfced110/src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt#L386) from `ConfigurationsToDependenciesTransformer`
- [ConfigurationsToDependenciesTransformer](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/12bd73e1db5f469c718cd659fb7d8c6019da6808/src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt#L21) is creating a set of dependencies and their scope used, e.g. `com.google.guava:guava` > `implementation`
- `LocateDependenciesTask` is [writing the set as JSON to disk](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/1925b6f2dab44a7305addb6cc38b6e7f7684d29a/src/main/kotlin/com/autonomousapps/tasks/LocateDependenciesTask.kt#L34) resulting in a file at `build/reports/dependency-analysis/main/intermediates/locations.json` that contains entries like
```
[
  {
    "identifier": "com.google.guava:guava",
    "configurationName": "implementation"
  },
  ...
]
```
- `locations.json` contains corretly both, dependencies to 3rd party libs like e.g. guava as well as dependencies to other Gradle modules of a multi-module build. But there are no versions.
- Therefore: as long as you only change the version, there is no reason for the `LocateDependenciesTask` to re-run. It will be up-to-date since the input still is the same and the output files are already present due to the Gradle cache. If the output of `LocateDependenciesTask` is up-to-date, the input to `ArtifactsAnalysisTask` is also up-to-date, etc.

Possible solutions could be:

1. `LocateDependenciesTask` is not cachable (easy quick-fix, but not optimal regarding runtime)
2. `LocateDependenciesTask` gets the dependencies from `ConfigurationsToDependenciesTransformer` with version information

Does this make sense to you?

**Comment by Paladinium** [comment] 2020-05-14 09:39
This workaround seems to work:

```
tasks.withType(ArtifactsAnalysisTask).configureEach {
	outputs.cacheIf { false }
}
```

**Comment by autonomousapps** [comment] 2020-05-14 17:04
Do you have a build scan from the failure? You can use `--scan` if you don't have the plugin applied.

**Comment by Paladinium** [comment] 2020-05-18 11:53
Gradle's JAR task has a property called [archiveVersion](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:archiveVersion) which defaults to `project.version`.

If you follow [this tutorial from Gradle](https://guides.gradle.org/creating-multi-project-builds/#configure_from_above), you see how they set the version on `subprojects`.

To reproduce, I added a [sample-project.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/4643848/sample-project.zip) for you with 2 subprojects, A and B, with A depending on B.

To reproduce the bug:

1. `unzip sample-project.zip`
2. `cd sample-project`
3. Clear the cache (in case you are doing trying this example several times): `rm -rf build-cache/`
3. `./gradlew --console=plain clean build`
4. `cat subproject-a/build/reports/dependency-analysis/main/intermediates/artifacts-pretty.json`
5. Observe that the file referenced contains the version as expected: sample-project/subproject-b/build/libs/subproject-b-1.0.0.jar
6. Change the version (you can also do it manually in build.gradle.kts): `sed -i -e 's/version = "1.0.0"/version = "1.0.1"/g' build.gradle.kts`
7 `./gradlew --console=plain clean build`

The last 'clean' is important to make sure the old JAR is gone and it results in this error:

```
* What went wrong:
Execution failed for task ':subproject-a:constantUsageDetectorMain'.
> A failure occurred while executing com.autonomousapps.tasks.ConstantUsageDetectionWorkAction
   > /devel/sample-project/subproject-b/build/libs/subproject-b-1.0.0.jar

```

If you disable the cache in `gradle.properties` by setting `org.gradle.caching = false`, you won't see any error. It is really in conjunction with the cache that you face this problem.

Here is the scan on the sample project where I went from version 1.0.1 to 1.0.2: https://scans.gradle.com/s/h57ai33i4uoma

**Comment by autonomousapps** [comment] 2020-05-18 19:26
Thank you, this is very helpful!

**Comment by autonomousapps** [comment] 2020-05-18 23:28
Ok, this is fixed and will be in the next release. The issue was that `ArtifactsAnalysisTask` had an input that was using `@Classpath`, which completely ignores _path_ to a file and only cares about content. Since I was dealing with jars, I thought this was correct, but this issue shows clearly that we also care about the path. Thanks so much for the reproducer.

**Closed** 2020-05-18 23:52 UTC
Labels: bug

**Comment by Paladinium** [comment] 2020-05-19 05:11
Thanks, @autonomousapps . Me and my team are impressed of what you are doing with this plugin. Great work!
