### ISSUE TITLE
runtimeOnly gets suggested but would break the build

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#671] opened 2022-05-13 09:55 UTC
**Build scan link**

Reproducer instead: [firebase-analytics.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/8685981/firebase-analytics.zip)

**Plugin version**

1.2.0

**Gradle version**

7.4.2

**(Optional) Android Gradle Plugin (AGP) version**

7.2.0

**`reason` output for bugs relating to incorrect advice**

```
----------------------------------------
You asked about the dependency 'com.google.firebase:firebase-analytics-ktx:21.0.0'.
You have been advised to change this dependency to 'runtimeOnly' from 'implementation'.
----------------------------------------

Shortest path from : to com.google.firebase:firebase-analytics-ktx:21.0.0:
:
\--- com.google.firebase:firebase-analytics-ktx:21.0.0

Source: debug, main
-------------------
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies runtimeOnly).

Source: release, main
---------------------
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies runtimeOnly).

Source: debug, test
-------------------
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies testRuntimeOnly).

Source: release, test
---------------------
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies testRuntimeOnly).
```

**Describe the bug**

I have a dependency on `com.google.firebase:firebase-analytics-ktx`, but only use classes from `com.google.android.gms:play-services-measurement-api`. The suggestion is to change the dependency to `runtimeOnly`. 

**To Reproduce**
1. ...

**Expected behavior**

I would have expected to get the advice to remove `com.google.firebase:firebase-analytics-ktx` because it's unused and add a depednency on `com.google.android.gms:play-services-measurement-api`.

**Additional context**

The `ComponentDiscoveryService` that is mentioned in `reason` is part of `com.google.firebase:firebase-common`

**Comment by autonomousapps** [comment] 2022-05-13 19:51
> I would have expected to get the advice to remove com.google.firebase:firebase-analytics-ktx because it's unused and add a depednency on com.google.android.gms:play-services-measurement-api.

To clarify, are you saying you see no advice regarding `com.google.android.gms:play-services-measurement-api`? Can you provide the `reason` output for that? That might relate to the fact that those are treated as part of an [implicit bundle](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt#L47-L50).

Do you also use the ignoreKtx option?

Looks like there's potentially some interaction between runtimeOnly, bundles, and ignoreKtx that will require some deeper modeling. Thanks for the report.

**Comment by gabrielittner** [comment] 2022-05-13 20:21
> To clarify, are you saying you see no advice regarding com.google.android.gms:play-services-measurement-api?
Yes, the only output is this:
```
Advice for :
Dependencies which should be removed or changed to runtime-only:
  runtimeOnly 'com.google.firebase:firebase-analytics-ktx:21.0.0' (was implementation)
```

> Can you provide the reason output for that?

```
----------------------------------------
You asked about the dependency 'com.google.android.gms:play-services-measurement-api:21.0.0'.
There is no advice regarding this dependency. It was removed because it matched a bundle rule.
----------------------------------------

Shortest path from : to com.google.android.gms:play-services-measurement-api:21.0.0:
:
\--- com.google.firebase:firebase-analytics-ktx:21.0.0
      \--- com.google.firebase:firebase-analytics:21.0.0
            \--- com.google.android.gms:play-services-measurement-api:21.0.0

Source: debug, main
-------------------
* Uses class com.google.firebase.analytics.FirebaseAnalytics (implies implementation).
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies runtimeOnly).

Source: release, main
---------------------
* Uses class com.google.firebase.analytics.FirebaseAnalytics (implies implementation).
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies runtimeOnly).

Source: debug, test
-------------------
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies testRuntimeOnly).

Source: release, test
---------------------
* Provides Android Services: [com.google.firebase.components.ComponentDiscoveryService] (implies testRuntimeOnly).
```


> Do you also use the ignoreKtx option?

No

**Comment by autonomousapps** [comment] 2022-05-14 00:35
Very helpful, thank you!

On May 13, 2022, GitHub ***@***.***> wrote:
> > To clarify, are you saying you see no advice regarding
> > com.google.android.gms:play-services-measurement-api?
> >  Yes, the only output is this:
> >
>
> Advice for : Dependencies which should be removed or changed to
> runtime-only: runtimeOnly 'com.google.firebase:firebase-analytics-
> ktx:21.0.0' (was implementation)
> > Can you provide the reason output for that?
> >
>
> ---------------------------------------- You asked about the
> dependency 'com.google.android.gms:play-services-measurement-
> api:21.0.0'. There is no advice regarding this dependency. It was
> removed because it matched a bundle rule.
> ---------------------------------------- Shortest path from : to
> com.google.android.gms:play-services-measurement-api:21.0.0: : \---
> com.google.firebase:firebase-analytics-ktx:21.0.0 \---
> com.google.firebase:firebase-analytics:21.0.0 \---
> com.google.android.gms:play-services-measurement-api:21.0.0 Source:
> debug, main ------------------- * Uses class
> com.google.firebase.analytics.FirebaseAnalytics (implies
> implementation). * Provides Android Services:
> [com.google.firebase.components.ComponentDiscoveryService] (implies
> runtimeOnly). Source: release, main --------------------- * Uses class
> com.google.firebase.analytics.FirebaseAnalytics (implies
> implementation). * Provides Android Services:
> [com.google.firebase.components.ComponentDiscoveryService] (implies
> runtimeOnly). Source: debug, test ------------------- * Provides
> Android Services:
> [com.google.firebase.components.ComponentDiscoveryService] (implies
> testRuntimeOnly). Source: release, test --------------------- *
> Provides Android Services:
> [com.google.firebase.components.ComponentDiscoveryService] (implies
> testRuntimeOnly).
> > Do you also use the ignoreKtx option?
> >
>
> No
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/671#issuecomment-1126434948>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PI5UC5ZFN7DTBET4QDVJ22VHANCNFSM5V23WOKQ>.
You are receiving this because you commented.Message ID:
<autonomousapps/dependency-analysis-android-gradle-
***@***.***>

**Comment by autonomousapps** [comment] 2022-05-14 19:09
@gabrielittner got a PR resolving this. Thanks for always providing a reproducer -- makes it so much easier to fix these issues.

**Comment by autonomousapps** [comment] 2022-05-14 20:15
Resolved via https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/672.

**Closed by autonomousapps** 2022-05-14 20:15 UTC
Labels: bug
