### ISSUE TITLE
Reported unused module but super class is needed

### ISSUE THREAD

**Issue by emartynov** [autonomousapps/dependency-analysis-android-gradle-plugin#60] opened 2020-02-07 00:48 UTC
**Gradle version**
6.0.1
**Android Gradle Plugin (AGP) version**
3.5.3

**Describe the bug**
I have module A class AA extends module B class BB. And module B class BB extends module C class CC. The module C is reported as non-used in module A but compilation fails:
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class BB, unresolved supertypes: CC
```

**Expected behavior**
Module C should not be reported as non-used in module A.

**Comment by autonomousapps** [comment] 2020-02-08 07:58
Is module B declaring module C as api?

**Comment by emartynov** [comment] 2020-02-10 21:47
Wow, I made ticket so generic, that I can not find the real reference in my project. Let me try to find it first.

**Comment by autonomousapps** [comment] 2020-03-01 21:02
@emartynov I'm going to close this for now, but feel free to re-open if/when you have more information.

**Comment by emartynov** [comment] 2020-03-17 14:13
@autonomousapps I think I found one example.

Clone project https://github.com/chrisbanes/tivi.

Run advices plugin and find next advice:

```
  {
    "dependency": {
      "identifier": ":presenter-episodedetails"
    },
    "toConfiguration": "implementation"
  },
```

I found it only one place, in `ui-episodedetails` module.

I changed it from `api` to `implementation` and got:

```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class app.tivi.episodedetails.EpisodeDetailsFragment, unresolved supertypes: app.tivi.episodedetails.EpisodeDetailsViewModel.FactoryProvider
```

**Comment by autonomousapps** [comment] 2020-03-23 22:00
Thanks, I'll take a look.

**Comment by autonomousapps** [comment] 2020-04-07 04:10
I believe there is a misunderstanding. I cloned the project and ran `./gradlew buildHealth` and looked at `advice-pretty.json` and see this:
```
{
  ":app": [
    {
      "dependency": {
        "identifier": ":presenter-episodedetails"
      },
      "toConfiguration": "implementation"
    },
...
```
what this means is that the `app` module should _add_ the `:presenter-episodedetails` project to the `implementation` configuration. It is **NOT** saying to remove it from any module's `api` configuration.

I'm going to close this is as not reproducible, but please feel free to re-open if you find a reproducer.

**Closed by autonomousapps** 2020-04-07 04:10 UTC
Labels: bug

**Comment by nwagu** [comment] 2024-03-23 15:51
@autonomousapps I am running into this too. I made a simple reproducer here https://github.com/nwagu/dagpbrepro. An Android project, with two modules (`librarya` and `libraryb`) added. `app` depends on both `librarya` and `libraryb`, and `librarya` declares a data class that implements an interface declared in `libraryb`. When I run `buildHealth` on that project or `app:projectHealth`, it recommends to remove `libraryb` depedency from `app`, which should not be since the superclass (the interface in libraryb) is needed.

**Comment by nwagu** [comment] 2024-03-23 16:09
Oh I see `buildHealth` report also recommends to use `api(project(":libraryb"))` in librarya. But this is not clear by running app:projectHealth only
