### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by Poojith** [autonomousapps/dependency-analysis-android-gradle-plugin#417] opened 2021-06-15 02:26 UTC
**Plugin version**
0.71.0

**Gradle version**
 6.6.1

**(Optional) Android Gradle Plugin (AGP) version**
Not an Android project

**Describe the bug**
One of the sub-projects throws a ZipException:

```
Task :abstractor-impl:analyzeJarMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':abstractor-impl::analyzeJarMain'.
> java.util.zip.ZipException: error in opening zip file

...
Caused by: java.util.zip.ZipException: error in opening zip file
        at com.autonomousapps.internal.JarAnalyzer.analyzeJar(JarAnalyzer.kt:61)
        at com.autonomousapps.internal.JarAnalyzer.asComponents(JarAnalyzer.kt:49)
        at com.autonomousapps.internal.JarAnalyzer.components(JarAnalyzer.kt:30)
        at com.autonomousapps.tasks.AnalyzeJarTask.action(AnalyzeJarTask.kt:91)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**To Reproduce**

Based on the known behavior of the plugin not extending to custom frameworks/projects, to circumvent the [no-op scenario](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/354#issuecomment-754182710), I manually added the `java-library` plugin to all the sub-projects. 

To reproduce, please try explicitly adding the `java-library` plugin to a non-Android Gradle service.

**Expected behavior**
The subproject should gracefully fail/provide more context when a zip artifact cannot be processed. 

**Additional context**

On adding `java-library`, most of the sub-projects work as expected by not evaluating to be a no-op. However, one of them fails with the aforementioned error. 

Additionally, it would help isolate the issue if details pertinent to the file are outputted.  My suspicion is that the plugin is unable to locate the zip file. Note: I've also noticed a similar error on another service where a `ZipException` of `zip END header not found` is thrown.

Is there a specific location where the `JarAnalyzer` reads the [components](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/37ed71da79a2092c59c6bf4554101df09bc20e54/src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt#L49) from?

**Comment by autonomousapps** [comment] 2021-06-15 18:19
Could you provide a minimal reproducer? I don't quite understand what you mean by
> To reproduce, please try explicitly adding the java-library plugin to a non-Android Gradle service.

What is "service" in this context? Also, the plugin has extensive tests that run against java-library projects.

**Comment by Poojith** [comment] 2021-06-15 19:16
Thank you for taking a look. By "service", I meant any non-Android project that runs on Gradle and requires explicit declarations to circumvent the [no-op scenario](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/354#issuecomment-754182710) you'd described. Basically, to deal with the no-op situation, I have explicit 'java-library' plugin declarations in the `build.gradle`, which works for the most part, except for a few sub-projects where this error is seen.

I'm trying to figure out if there's an easy way to share a minimal reproducer that has a few of our custom configurations. Meanwhile, is there a specific location where the JarAnalyzer reads the components from? That could help narrow down on where the Zip artifacts are attempted to be read from in our project.

**Comment by autonomousapps** [comment] 2021-06-17 18:45
What kind of project do you have? Do you have a build scan? The "no-op scenario" you describe is better described as "this plugin is only designed to work with certain other plugins, such as java-library." If the plugin no-ops, it's because it doesn't understand how to analyze your project. Trying to circumvent that is not recommended and not supported.

**Comment by Poojith** [comment] 2021-06-24 22:32
@autonomousapps , thank for you taking a look. The issue that I was describing is solved by my teammate with this PR - https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/429

**Comment by autonomousapps** [comment] 2021-06-25 01:36
Got it. Thanks for letting me know. I'll close this now.

**Closed by autonomousapps** 2021-06-25 01:36 UTC
Labels: question
