### ISSUE TITLE
`Unsupported class file major version 63`

### ISSUE THREAD

**Issue by boris-petrov** [autonomousapps/dependency-analysis-android-gradle-plugin#798] opened 2022-10-26 05:07 UTC
**Plugin version**
1.13.1

**Gradle version**
7.5.1

**Describe the bug**
Running `gradle buildHealth` on the `build.gradle` file below leads to:

```
Execution failed for task ':explodeJarMain'.
> A failure occurred while executing com.autonomousapps.tasks.ExplodeJarTask$ExplodeJarWorkAction
   > Unsupported class file major version 63
```

**To Reproduce**
`build.gradle`:
```gradle
plugins {
	id 'antlr'
	id 'com.autonomousapps.dependency-analysis' version '1.13.1'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.apache.lucene:lucene-analysis-common:9.4.1'
}
```

**Expected behavior**
That to work.

**Additional context**
I've only added the `antlr` plugin so that `buildHealth` runs `explodeJar*` tasks - I couldn't make it do that without it.
Downgrading `lucene` to `9.3.0` fixes the issue.

**Comment by JacksonBailey** [comment] 2022-11-13 18:38
I have this problem too but don't use lucene. Judging by the error we are both getting (`Unsupported class file major version 63`) I think the problem is class files compiled for Java 19. In the [change log for lucene 9.4.0][changelog] I found this mentioned, [MR-JAR rewrite of MMapDirectory with JDK-19 preview Panama APIs (>= JDK-19-ea+23)][pr]. To me this seems to indicate 9.4.0 and up use Java 19.

In my project I am using Java 19 (via toolchain) and get the same error you do. When I change it to 18 (or even 17) I don't get the error. So I think the problem is that this doesn't work with Java 19.

[changelog]: https://lucene.apache.org/core/9_4_1/changes/Changes.html#v9.4.0.new_features
[pr]: https://github.com/apache/lucene/pull/912

**Comment by uschindler** [comment] 2022-11-14 15:41
Lucene only has some class file in META-INF/versions/19.
Lucene 9.4 is still on Java 11, it is only some class files for newer Java versions.

I think the plugin should either:
- Do not look into class files it does not undertsand (maybe print a warning, optionally)
- Exclude Java versions from Multi-Release-JARs (which Lucene uses).

**Comment by autonomousapps** [comment] 2022-11-14 17:56
Thanks for the issue and the discussion. I'm open to contributions if someone wants to try to fix this. I can also take a look but I can't make any promises on timing right now.

**Comment by JacksonBailey** [comment] 2022-11-14 23:31
@autonomousapps I think I've identified the problem. The version of asm you use in [`asm-relocated`](https://github.com/autonomousapps/asm-relocated/blob/master/build.gradle) is 9.2. [Here](https://asm.ow2.io/versions.html) I see that in 9.3 they add support for Java 19 (and in 9.4 Java 20).

Is there any reason in particular why you used the `asm-relocated` to put it in a different package? If not then I can look into fixing the imports and using the normal `asm` and `asm-tree` dependencies this way upgrading to future versions like 9.5 for Java 21 will be easy.

**Comment by uschindler** [comment] 2022-11-15 20:31
For Forbiddenapis also using ASM, the shading is done live during build. I'd suggest to compile against the standard compile classpath with real ASM (as done in the PR and finally use the Maven shade Plugin to rewrite all class files during packaging. That's easier to maintain. Of course you need to make sure which dependencies you shade into the main jar.

**Comment by autonomousapps** [comment] 2022-11-15 23:33
I'd rather not change my whole build process at this time.

**Comment by autonomousapps** [comment] 2022-11-29 20:31
The issue is now resolved, although there is an open PR adding additional test coverage. I'm going to close the issue, but I do still intend to look more at the PR.

**Closed by autonomousapps** 2022-11-29 20:31 UTC
Labels: bug, toolchain:java
