### ISSUE TITLE
Kotlin Multi Platform Unresolved reference issues

### ISSUE THREAD

**Issue by mustafaozhan** [autonomousapps/dependency-analysis-android-gradle-plugin#365] opened 2021-02-11 11:25 UTC
**Build scan link**
https://github.com/CurrencyConverterCalculator/CCC/runs/1873398975?check_suite_focus=true

**Plugin version**
0.71.0

**Gradle version**
6.8.2

**Android Gradle Plugin (AGP) version**
7.0.0-alpha05

**Describe the bug**
If I enable library in my Kotlin Multi Platform project the `buildHealth` tasks works fine but then I realised that it causes  `Unresolved reference` in native packages, I had comment the plugin in order to get succesful build in CI

**To Reproduce**
just simple running `./gradlew build`

**Expected behavior**
It should not affect `./gradlew build` task

**Comment by autonomousapps** [comment] 2021-04-18 18:05
Could you provide a reproducer? This plugin does not yet officially support KMP (I have no tests for it), and what support it does have is sort of accidental.

**Comment by autonomousapps** [comment] 2022-03-26 19:39
Duplicate of https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/228

**Closed by autonomousapps** 2022-03-26 19:39 UTC
Labels: question
