### ISSUE TITLE
Support other JVM languages

### ISSUE THREAD

**Issue by oehme** [autonomousapps/dependency-analysis-android-gradle-plugin#576] opened 2022-01-26 18:38 UTC
The [ClassAnalysisTask](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/4989df40e8fcda809fd7fe6a8f3fc8349a4e724b/src/main/kotlin/com/autonomousapps/tasks/classAnalysisTasks.kt#L170) has hardcoded file collections for Java and Kotlin. Instead, it could have a single file collection and use `sourceSet.output.classesDirs` to get all the classes a project has. This should make the dependency analysis work with languages like Scala and Groovy.

**Comment by autonomousapps** [comment] 2022-01-27 06:04
Thanks for the request, and the hint.

**Comment by autonomousapps** [comment] 2022-05-22 23:27
I am not aware of any _known, specific_ issues with analyzing other JVM languages. So long as either the `java-library` or `application` plugin is applied, then this should work with any JVM language. I'm going to close this issue as non-reproducible. If you know of any specific issues, please provide a reproducer.

**Closed by autonomousapps** 2022-05-22 23:27 UTC
Labels: enhancement

**Comment by autonomousapps** [comment] 2022-05-28 18:39
Btw, I was able to use your hint [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/681). It's an important step, but because the plugin also analyzes source directly, I think I still need to specifically add support for each additional language.
