### ISSUE TITLE
Remove "kotlin-stdlib-jdk8" but it's not declared anywhere?

### ISSUE THREAD

**Issue by ColtonIdle** [autonomousapps/dependency-analysis-android-gradle-plugin#444] opened 2021-08-01 23:57 UTC
**Plugin version**
0.75.0

**Gradle version**
7.1.1

**(Optional) Android Gradle Plugin (AGP) version**
7.1.0=alpha05

**Describe the bug**
```
Advice for project :MyCustomViewLib
Unused dependencies which should be removed:
- api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.10")
```

shows up even though I don't ref stdlib anywhere?

**To Reproduce**
This is my build file
```
plugins {
    id("com.android.library")
    id("kotlin-android")
}

android {
    compileSdk = 29

    defaultConfig {
        minSdk = 26
        targetSdk = 29
    }

    buildTypes {
        named("release") {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    sourceSets { getByName("main").assets.srcDirs("assets") }

}

dependencies {
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
    implementation("androidx.appcompat:appcompat:1.4.0-alpha03")
    api("androidx.core:core:1.7.0-alpha01")
    implementation("androidx.customview:customview:1.1.0")
}

```

**Comment by autonomousapps** [comment] 2021-08-02 02:55
You're twenty versions behind! 🙂

On August 1, 2021, GitHub ***@***.***> wrote:
> Plugin version
>  0.54.0
>
> Gradle version
>  7.1.1
>
> (Optional) Android Gradle Plugin (AGP) version
>  7.1.0=alpha05
>
> Describe the bug
>
> Advice for project :MyCustomViewLib Unused dependencies which should
> be removed: - api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.10")
> shows up even though I don't ref stdlib anywhere?
>
> To Reproduce
>  This is my build file
>
> plugins { id("com.android.library") id("kotlin-android") } android {
> compileSdk = 29 defaultConfig { minSdk = 26 targetSdk = 29 }
> buildTypes { named("release") { isMinifyEnabled = false proguardFiles(
> getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-
> rules.pro") } } sourceSets {
> getByName("main").assets.srcDirs("assets") } } dependencies {
> implementation(fileTree(mapOf("dir" to "libs", "include" to
> listOf("*.jar")))) implementation("androidx.appcompat:appcompat:1.4.0-
> alpha03") api("androidx.core:core:1.7.0-alpha01")
> implementation("androidx.customview:customview:1.1.0") }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/444>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5POAYANAYBI2HTXICZLT2XNQXANCNFSM5BLUSWLA>.

**Comment by ColtonIdle** [comment] 2021-08-02 21:10
@autonomousapps right after I submitted the bug I updated the version since it was a copy/pasta error. Sorry! I'm on latest!

**Comment by autonomousapps** [comment] 2021-08-02 23:07
Do you have a build scan?

**Comment by ColtonIdle** [comment] 2021-08-02 23:23
Nope. I have a couple of tiny little repros like this. Would a small repro project be better off?

**Comment by autonomousapps** [comment] 2021-08-09 06:33
`org.jetbrains.kotlin:kotlin-stdlib-jdk8` is added I think by the Kotlin plugin.

At any rate, a small repro would be useful, yes.

**Comment by ColtonIdle** [comment] 2021-08-09 14:33
Sorry. In the midst of a job change so I will not get back to this for some time. Feel free to close if you must!

**Comment by bartek-wesolowski** [comment] 2022-02-01 10:12
I'm having the same issue with the latest version of the plugin. I'll try to provide a small project on which you can reproduce the issue.

**Comment by autonomousapps** [comment] 2022-02-02 02:31
Great, a reproducer is really key here.

**Comment by bartek-wesolowski** [comment] 2022-02-10 09:45
This problem appears for modules without unit tests. Here's how to reproduce it in the simplest way:
- Create a new empty Android project in Android Studio
- Add the Gradle Dependency Analysis Plugin (the current version is 1.0.0-rc01)
- Run `./gradlew app:projectHealth` - it will say that `material` and `core-ktx` are unused, which is true
- Remove `ExampleUnitTest`
- Run `./gradlew app:projectHealth` - it will indicate that `junit` is unnecessary but also that `api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10")` is unused when there's no explicit dependency on it

**Comment by autonomousapps** [comment] 2022-02-14 07:33
What you've described is the somewhat unusual situation where you have the Kotlin plugin applied but no Kotlin source code visible to this plugin (there might be Kotlin source in the androidTest source set, but this plugin doesn't analyze that yet). Since the Kotlin plugin automatically adds `api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:<<kotlin version>>"` to your project, that's why you see this advice. In fact, the plugin almost should advise you to remove the kotlin-android plugin 🤔 

One of the problems is that Gradle provides no way to tell if a dependency has been added by a user, directly in their build script, or if a dependency has been added by a plugin.

I think the conclusion I'm arriving at is that this is a minor case that's of a lower priority. You can workaround this by configuring the plugin to filter out such advice. For example:
```groovy
// root build.gradle
dependencyAnalysis {
  issues {
    onUnusedDependencies {
      exclude('org.jetbrains.kotlin:kotlin-stdlib-jdk8')
    }
  }
}
```

**Comment by bartek-wesolowski** [comment] 2022-02-14 23:05
You're right. I guess we can close the issue then.

**Comment by autonomousapps** [comment] 2022-02-15 00:34
I'm willing to leave it open for now. I'm simply saying I can't prioritize it at this time.

**Comment by autonomousapps** [comment] 2022-03-26 19:08
In the interests of cleaning up the list of open issues, I'm going to close this as works-as-intended. Feel free to reopen if you think it actionable. Thanks.

**Closed by autonomousapps** 2022-03-26 19:08 UTC
Labels: bug
