### ISSUE TITLE
Plugin fails to analyze Dagger usages

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#479] opened 2021-09-19 13:24 UTC
**Build scan link**

Reproducer [kapt-dagger.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/7192154/kapt-dagger.zip)

**Plugin version**

0.78.0

**Gradle version**

7.0 and 7.2

**Describe the bug**

When Dagger is used with kapt the plugin will print `Could not reflectively access processor class dagger.internal.codegen.ComponentProcessor` and will then go ahead to suggest

```
Plugin advice:
- kotlin-kapt: this project has the kotlin-kapt (org.jetbrains.kotlin.kapt) plugin applied, but no annotation processors (or no used annotation processors), which is redundant.
```

**To Reproduce**
1. Add Dagger as a kapt dependency

**Expected behavior**

Plugin does not fail to access the Dagger processor and does not suggest to remove kapt.

**Additional context**

I wonder if the behavior should generally be different if the access to a processor class fails. Maybe a different message for the plugin advice? In bigger builds it's easy to miss the "Could not reflectively access ..." message. I can open a feature request for that if you think it makes sense.

**Comment by autonomousapps** [comment] 2021-09-19 17:25
Thanks for the reproducer. I actually just noticed this myself the other day but didn't have time to investigate. This makes it so much easier.

Regarding "Could not reflectively access...", what do you think would be a better solution? I'm open to improving this use-case. Warnings-as-errors? Something else?

**Comment by gabrielittner** [comment] 2021-09-19 19:31
I was thinking that the plugin advice would say something like "Could not determine whether kapt is used because processor ... could not be accessed" instead of recommending the removal of kapt. That way even if you miss the log beforehand it's clear from the actual output. Currently you'd probably try removing kapt and then realize it was actually needed when things  don't build anymore. It could still use the plugin advice severity

**Comment by autonomousapps** [comment] 2021-09-19 21:47
That might be feasible. Would you mind filing a separate feature request for that?

**Comment by autonomousapps** [comment] 2021-09-22 06:18
This is pretty interesting. The dagger AP has a pretty complex initialization compared to other APs I've looked at. It even uses Dagger itself (sigh). Here's the top of the stacktrace from the failing `init()` call:
```
> Task :settings:findDeclaredProcsDebug                                                                                                                                      
Trying to initialize annotation processor with type dagger.internal.codegen.ComponentProcessor                                   
Could not initialize dagger.internal.codegen.ComponentProcessor. May not be able to get supported annotation types.          
java.lang.NoSuchMethodError: 'java.lang.Object dagger.internal.Preconditions.checkNotNullFromProvides(java.lang.Object)'                                                     
        at dagger.internal.codegen.ProcessingEnvironmentModule_DaggerElementsFactory.daggerElements(ProcessingEnvironmentModule_DaggerElementsFactory.java:39)
        at dagger.internal.codegen.ProcessingEnvironmentModule_DaggerElementsFactory.get(ProcessingEnvironmentModule_DaggerElementsFactory.java:30)
        at dagger.internal.codegen.ProcessingEnvironmentModule_DaggerElementsFactory.get(ProcessingEnvironmentModule_DaggerElementsFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)                                                                                                              
        at dagger.internal.codegen.validation.InjectBindingRegistryImpl_Factory.get(InjectBindingRegistryImpl_Factory.java:54)              
        at dagger.internal.codegen.validation.InjectBindingRegistryImpl_Factory.get(InjectBindingRegistryImpl_Factory.java:14)                  
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)                                                                                                              
        at dagger.internal.codegen.DaggerComponentProcessor_ProcessorComponent.injectComponentProcessor(DaggerComponentProcessor_ProcessorComponent.java:741)
        at dagger.internal.codegen.DaggerComponentProcessor_ProcessorComponent.inject(DaggerComponentProcessor_ProcessorComponent.java:736)
        at dagger.internal.codegen.ComponentProcessor.processingSteps(ComponentProcessor.java:127)                 
        at dagger.shaded.androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor.steps(JavacBasicAnnotationProcessor.kt:41)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.init(BasicAnnotationProcessor.java:121)                                    
        at com.autonomousapps.tasks.FindDeclaredProcsTask.tryInit(FindDeclaredProcsTask.kt:166)
```
So, at the very least, it's choking on the `NoSuchMethodError` because it can't find `dagger.internal.Preconditions.checkNotNullFromProvides`. This makes sense, because I'm loading the AP class dynamically at runtime, in a classloader that doesn't also have this other required class. I dug through the decompiled bytecode a bit (for some reason, IDEA can't download the source jars?), and in this case, it is required to call `init()` in order to then call `getSupportedAnnotationTypes()`.

So there are a couple of options:
1. Punt and create a list of known annotation types that dagger supports. Meh.
2. Treat dagger a bit specially, which may be warranted given its prominence, and try to appease it by creating a custom classloader and loading more stuff at runtime.
3. Something else??

**Comment by autonomousapps** [comment] 2021-09-23 05:52
@gabrielittner you can workaround this right now by updating your `build.gradle`:
```groovy
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath("com.google.dagger:dagger:2.38.1")
    classpath("com.squareup:javapoet:1.13.0")
  }
}
```
The annotation processor analysis is failing because it can't initialize the dagger AP due to classes from these dependencies missing from the build classpath. I will be working on resolving this transparently.

**Comment by gabrielittner** [comment] 2021-09-23 20:13
Thanks for the workaround, that's helpful 👍 

I've opened the extra feature request for our message discussion.

**Comment by autonomousapps** [comment] 2021-09-25 00:59
Resolved, will be in the next release.

**Closed** 2021-09-25 00:59 UTC
Labels: bug
