### ISSUE TITLE
buildHealth fails with Gradle 8.1 when 'org.gradle.configuration-cache.problems=warn'

### ISSUE THREAD

**Issue by ianbrandt** [autonomousapps/dependency-analysis-android-gradle-plugin#885] opened 2023-04-04 16:22 UTC
**Build scan link**
https://scans.gradle.com/s/dojquhoalcdyc

**Plugin version**
1.19.0

**Gradle version**
8.1 RC3

**(Optional) Android Gradle Plugin (AGP) version**
N/A

**Describe the bug**
`buildHealth` fails with Gradle 8.1 RC3 when [`org.gradle.configuration-cache=true` and `org.gradle.configuration-cache.problems=warn` are set](https://github.com/sdkotlin/sd-kotlin-talks/blob/707a21a583fad8ffaf2ee13e96367267973d74dd/gradle.properties#L2-L3) in gradle.properties:

```text
Execution failed for task ':effective-kotlin:graphViewMain'.
> lateinit property compileClasspath has not been initialized
```

If I comment out `org.gradle.configuration-cache.problems=warn` then `buildHealth` succeeds.

**To Reproduce**
Reproducer: https://github.com/sdkotlin/sd-kotlin-talks/tree/707a21a583fad8ffaf2ee13e96367267973d74dd

1. Run `gradlew buildHealth`.

**Expected behavior**
`buildHealth` succeeds.

**Additional context**
Possibly related: https://github.com/gradle/gradle/issues/24636.

**Comment by autonomousapps** [comment] 2023-04-21 15:16
Thanks for the report. This plugin does not yet support the configuration cache, but doing so is on the near-term roadmap.

**Comment by autonomousapps** [comment] 2023-04-21 15:16
Closing as duplicate of https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/306

**Closed by autonomousapps** 2023-04-21 15:16 UTC
